# Generated by Django 5.0 on 2025-10-29 08:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PavementAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/pavement/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('overall_condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], max_length=20)),
                ('distress_type', models.CharField(choices=[('none', 'No Distress'), ('transverse', 'Transverse Crack'), ('longitudinal', 'Longitudinal Crack'), ('alligator', 'Alligator Crack'), ('pothole', 'Pothole'), ('multiple', 'Multiple Distress Types')], default='none', max_length=20)),
                ('severity_score', models.FloatField(default=0.0)),
                ('crack_density', models.FloatField(default=0.0)),
                ('confidence_level', models.FloatField(default=0.0)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('ai_description', models.TextField(blank=True, help_text='AI-generated description')),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
